# Generated by Django 3.2.5 on 2021-07-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_eventos_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='local',
            field=models.TextField(blank=True, null=True, verbose_name='Local/Endereço'),
        ),
    ]
